FROM node:latest
ADD node_modules /node-api/node_modules/
ADD bin /node-api/bin/
ADD src /node-api/src
#RUN npm install -g node-inspector
#RUN npm install pm2 -g
#RUN npm install express
#RUN npm install ip
#RUN npm install mongoose
#RUN npm install babel -g
#RUN npm install --save-dev gulp-babel babel-preset-es2015
#RUN npm install nodemon -g